.TH "numad" "8" "0.5.0" "Bill Gray" "Administration"
.SH "nuamd"
.LP 
numad \- A user\-level daemon that provides advice and managment for optimum use of CPUs and memory on systems with NUMA topology.
.SH "SYNTAX"
.LP 
numad [\fI\-dhvV\fP]
.br 
.LP 
numad  [\fI\-i max_interval[:min_interval]\fP]
.br 
.LP 
numad  [\fI\-l log_level\fP]
.br 
.LP 
numad  [\fI\-w NCPUS[:MB]\fP]
.br 
.LP 
numad  [\fI\-u target_utilization\fP]
.br 
.SH "DESCRIPTION"
.LP 
Numad is a system daemon that monitors NUMA topology and usage. It will attempt to locate 
processes for optimum NUMA locality, dynamically adjusting to changing system conditions. Numad also provides guidance to assist management applications with initial manual binding of CPU and memory resources for their processes.
.SH "OPTIONS"
.LP 
.TP 
\fB\-h\fR
Output help information and exit.
.TP 
\fB\-i\fR <\fImax_interval[:min_interval]\fP>
Sets the time interval that numad waits between system scans, in seconds <\fImax_interval\fP>. Default <\fImax_interval\fP> is 15 seconds, default <\fImin_interval\fP> is 5 seconds.
Setting a <\fImax_interval\fP> of zero will cause the daemon to exit.
.TP 
\fB\-u  <\fItarget_utilization\fP>
Set the desired maximum consumption percentage of a node. Default is 85%
.TP 
\fB\-d\fR
Debug output, sets the log level to LOG_DEBUG.
.TP 
\fB\-v\fR
Verbose output, sets the log level to LOG_INFO.
.TP 
\fB\-l\fR <\fIlog_level\fP>
Sets the log level to <\fIlog_level\fP>.
.TP 
\fB\-V\fR
Output version information and exit.
.TP 
\fB\-w\fR <\fINCPUS[:MB]\fP>
Queries numad for the best CPUs to bind an entity that needs <\fINCPUS\fP>. Optionally, the amount of memory for the entity can be specified as well <\fI:MB\fP> so numad can pick CPUS on a node with adequate free memory. Output of this option is a string that contains a node list. For example: 2\-3,6.
.SH "FILES"
.LP 
\fI/usr/bin/numad\fP 
.br 
\fI/var/log/numad.log\fP 
.br 
\fI/var/run/numad.pid\fP 
.SH "ENVIRONMENT VARIABLES"
.LP 
.TP 
None.
.SH "EXAMPLES"
.LP 
Numad is normally run a system daemon and should be managed by the 
standard init mechanisms of the host.
.LP  
To run this program manually type:
.LP 
/usr/bin/numad
.SH "AUTHORS"
.LP 
Bill Gray <bgray@redhat.com>
.SH "SEE ALSO"
.LP 
numactl(8)
